### PR TITLE
Add better integration for Linux

### PR DESCRIPTION
**Pull request by City-busz**
Add AppStream metadata, add installation target.

### CODE REVIEW

**Comment by vkohaupt** [comment]
Hello City-busz,
As I wrote in other places, I will not support "make install" or "metadata". Because the distros can do that much better.
Thank you for your understanding.

**Comment by City-busz** [comment]
This is a distro-agnostic solution that makes it easier for distributions to provide proper packages.

**Comment by SCOTT-HAMILTON** [comment]
It's indeed [easier](https://github.com/vkohaupt/vokoscreenNG/issues/139) for me to package vokoscreenNG with this fix . @City-busz even if this doesn't get to upstream, could you update your fix for latest release 3.0.8, in nixpkgs, it's preferred to avoid adding patch files in the repo, we prefer pointing to a commit patch than to add patches files in the repo?

**Comment by vkohaupt** [comment]
@SCOTT-HAMILTON
I think you'd better write yourself a patch or an install script.
In my eyes it is not good to rely on a make-install and a make-uninstall.

**Pull request closed without merging**
